### ISSUE TITLE
Using civicrm_membership_log?

### ISSUE THREAD

**Issue by MegaphoneJon** [spelcaster/dcw.hugocarmo.membershiphistory#5]
Hello Hugo,

Welcome to the CiviCRM community!  I was very impressed by the PR you just submitted; I know it's a one-line fix, but I personally looked long and hard at a very similar bug in CiviCRM.

I noticed this extension - and I wanted to make sure you were aware of `civicrm_membership_log`.  It's a table that exists in Civi but isn't exposed to the API or UI.  It seems to contain much of the same information you're storing.

Finally - it seems like multiple people are working on the same functionality all of a sudden: https://civicrm.stackexchange.com/questions/19758/civicrm-membership-component/19769#19769

Are these colleagues? Or is this perhaps a coding test for a job? I just wanted to make sure you were aware - and thanks again for your great work.

**Comment by spelcaster** [comment]
Hi Jon,

Thank you so much, these kind of interaction is the real thing, that's what make us feel in love with open source.

You know, bug hunt is an ungrateful work, sometimes you spend days to discover that one line solve your problems, but the research process is very pleasant.

So, talking back about this extension, it's part of a challenge, probably the other guys are doing the same thing, but I didn't know about civicrm_membership_log either way, I'll take a look in this table.

Thank you to take your time to check my work.
